#!/usr/bin/env bash

# File        :  haproxy
#
# Purpose     :  A fast and reliable http reverse proxy and load balancer launch/terminate/... script
#
# Copyright   :  Written by and Copyright (C) 2023-03-17
#                Miles Guo. komg@hotmail.com
#
#                This program is free software; you can redistribute it
#                and/or modify it under the terms of the GNU General
#                Public License as published by the Free Software
#                Foundation; either version 2 of the License, or (at
#                your option) any later version.
#
#                This program is distributed in the hope that it will
#                be useful, but WITHOUT ANY WARRANTY; without even the
#                implied warranty of MERCHANTABILITY or FITNESS FOR A
#                PARTICULAR PURPOSE.  See the GNU General Public
#                License for more details.
#
#                The GNU General Public License should be included with
#                this file.  If not, you can view it at
#                http://www.gnu.org/copyleft/gpl.html
#                or write to the Free Software Foundation, Inc.,
#                51 Franklin Street, Fifth Floor, Boston, MA 02110-1301,
#                USA
#
# Modification : If you modify this file please consider whether your 
#                changes ought to be passed back to me.
#

cd "$(dirname "$0")"

usage() {
  cat <<EOF
Usage: $0 {start|stop|restart|reload|condrestart|check}
EOF
  exit 1
}

[ $# -ne 1 ] && usage

. rc.common

BASENAME=`basename $0`
# check haproxy
BINPATH=/usr/local/bin
BINFILE=$BINPATH/$BASENAME
if [ ! -x $BINFILE ]; then
  echo "Sorry, you haven't installed $BASENAME yet."
  echo "Please refer to the readme.md for the solution."
  exit 1
fi

CFGFILE=$PWD/$BASENAME.cfg
[ -f $CFGFILE ] || exit 1
data_dir=$PWD/run/$BASENAME
PIDFILE=$data_dir/$BASENAME.pid

RETVAL=0

start() {
  if [ -e $PIDFILE ]; then
    echo "$BASENAME is already running."
    return 0
  fi

  quiet_check
  if [ $? -ne 0 ]; then
    echo "Errors found in configuration file, check it with '$0 check'."
    return 1
  fi

  if [ ! -d "$data_dir" ]; then
    echo "Creating directory $data_dir"
    mkdir -p -m 700 "$data_dir"
  fi

  echo "Starting $BASENAME."
#  $BINFILE -D -f $CFGFILE -p $PIDFILE >$LOGFILE 2>&1
  $BINFILE -D -f $CFGFILE -p $PIDFILE 2> /dev/null
  RETVAL=$?
  echo
  return $RETVAL
}

stop() {
  if [ -e $PIDFILE ]; then
    echo "Shutting down $BASENAME."
    pid=$(GetPID $BASENAME)
    kill -USR1 "$pid"
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && rm -f $PIDFILE
    return $RETVAL
  else
    echo "$BASENAME is not running."
    return 0
  fi
}

restart() {
  quiet_check
  if [ $? -ne 0 ]; then
    echo "Errors found in configuration file, check it with '$0 check'."
    return 1
  fi
  stop
  start
}

reload() {
  if [ ! -e $PIDFILE ]; then
    echo "$BASENAME is not running."
    return 1
  fi

  quiet_check
  if [ $? -ne 0 ]; then
    echo "Errors found in configuration file, check it with '$0 check'."
    return 1
  fi

  $BINFILE -D -f $CFGFILE -p $PIDFILE -sf $(cat $PIDFILE) 2> /dev/null
}

check() {
  $BINFILE -c -q -V -f $CFGFILE
}

quiet_check() {
  $BINFILE -c -q -f $CFGFILE
}

condrestart() {
  if [ ! -e $PIDFILE ]; then
    echo "$BASENAME is not running."
    return 1
  fi

  quiet_check
  if [ $? -ne 0 ]; then
    echo "Errors found in configuration file, check it with '$0 check'."
    return 1
  fi

  [ -e $PIDFILE ] && restart || :
}

##
# Generic action handler
##
case "$1" in
  start       ) start;;
  stop        ) stop;;
  restart     ) restart;;
  reload      ) reload;;
  condrestart ) condrestart;;
  check       ) check;;
  *           ) usage;;
esac
 
exit $?

## End of haproxy