#!/usr/bin/env bash

# File        :  privoxy
#
# Purpose     :  A Privoxy Enhancing Proxy launch/terminate/... script
#
# Copyright   :  Written by and Copyright (C) 2023-04-26
#                Miles Guo. komg@hotmail.com
#
#                This program is free software; you can redistribute it
#                and/or modify it under the terms of the GNU General
#                Public License as published by the Free Software
#                Foundation; either version 2 of the License, or (at
#                your option) any later version.
#
#                This program is distributed in the hope that it will
#                be useful, but WITHOUT ANY WARRANTY; without even the
#                implied warranty of MERCHANTABILITY or FITNESS FOR A
#                PARTICULAR PURPOSE.  See the GNU General Public
#                License for more details.
#
#                The GNU General Public License should be included with
#                this file.  If not, you can view it at
#                http://www.gnu.org/copyleft/gpl.html
#                or write to the Free Software Foundation, Inc.,
#                51 Franklin Street, Fifth Floor, Boston, MA 02110-1301,
#                USA
#
# Modification : If you modify this file please consider whether your 
#                changes ought to be passed back to me.
#

cd "$(dirname "$0")"

usage() {
  cat <<EOF
Usage: $0 {start|stop|restart}
EOF
  exit 1
}

[[ $# -ne 1 ]] && usage

. rc.common

BASENAME=`basename $0`

# check privoxy
BINPATH=/usr/local/sbin
BINFILE=$BINPATH/$BASENAME
[[ ! -x $BINFILE ]] && {
  echo "Sorry, you haven't installed $BASENAME yet."
  echo "Please refer to the readme.md for the solution."
  echo
  exit 1
}

CFGFILE=$PWD/$BASENAME.cfg
[[ -f $CFGFILE ]] || {
  echo "Sorry, I can't find $CFGFILE, that is used to with $BASENAME."
  echo
  exit 1
}

data_dir=$PWD/run/$BASENAME
PIDFILE=$data_dir/$BASENAME.pid

RETVAL=0

start () {
  [[ -e $PIDFILE ]] && {
    echo "$BASENAME is already running."
    echo
    RETVAL=0
    return $RETVAL
  }
  [[ ! -d "$data_dir" ]] && mkdir -p -m 700 "$data_dir" >/dev/null 2>&1
  echo "Starting $BASENAME enhancing proxy."
  echo
  $BINFILE --no-daemon --pidfile $PIDFILE $CFGFILE >/dev/null 2>&1 &
  RETVAL=$?
  return $RETVAL
}

stop () {
  [[ ! -e $PIDFILE ]] && {
    echo "$BASENAME is not running."
    echo
    RETVAL=0
    return $RETVAL
  }
  echo "Shutting down $BASENAME."
  echo
  pid=$(GetPID $BASENAME)
  kill -TERM "$pid"
  RETVAL=$?
  [[ $RETVAL -eq 0 ]] && rm -f $PIDFILE >/dev/null 2>&1
  return $RETVAL
}

restart () {
  [[ ! -e $PIDFILE ]] && {
    stop
    start
    RETVAL=$?
    return $RETVAL
  }
  echo "Restarting $BASENAME enhancing proxy."
  echo
  pid=$(GetPID $BASENAME)
  kill -HUP "$pid"
  RETVAL=$?
  return $RETVAL
}

##
# Generic action handler
##
case "$1" in
  start   ) start;;
  stop    ) stop;;
  restart ) restart;;
  *       ) usage;;
esac
 
exit $?

## End of privoxy